/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youtubedownloader;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;
/**
 *
 * @author himel
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        JPopupMenu menu = new JPopupMenu();
        Action paste = new DefaultEditorKit.PasteAction();
        paste.putValue(Action.NAME, "Paste");
        paste.putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke("control V"));
        menu.add( paste );
        txtUrl.setComponentPopupMenu(menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUrl = new javax.swing.JTextField();
        cmbFormat = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Youtube Downloader");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 242, 246));

        txtUrl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUrl.setDragEnabled(true);

        cmbFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Format---" }));
        cmbFormat.setEnabled(false);
        cmbFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormatActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(240, 237, 228));
        jButton1.setText("Download");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(248, 243, 232));
        jButton2.setText("Get Video Format");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 36, 36));
        jLabel1.setText("YouTube Video Downloader Gui Free");

        jButton3.setBackground(new java.awt.Color(235, 249, 249));
        jButton3.setForeground(new java.awt.Color(170, 175, 172));
        jButton3.setText("About");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(cmbFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Downloading dl = new Downloading();
        jButton2.setEnabled(false);
        cmbFormat.setEnabled(false);
        dl.setVisible(true);
        String url = "" ;
         String code = cmbFormat.getSelectedItem().toString();
         int dcode;
         String VideoF = code.split("-")[0].trim();
         dcode = Integer.parseInt(VideoF);
         int progValue = 0;
         System.out.println("Selected Format Code is :"+ VideoF);
         url = txtUrl.getText();
         if (cmbFormat.getSelectedIndex() < 1){
             JOptionPane.showMessageDialog(null,"Please Select a Vido Format");
         }
         
         try {
            String UserName = System.getProperty("user.name");
            Process p = Runtime.getRuntime().exec("youtube-dl -o "+"/home/"+UserName+"/Desktop/%(title)s.%(ext)s"+" -f "+dcode+" "+ url);
            BufferedReader stdInput = new BufferedReader(new 
            InputStreamReader(p.getInputStream()));
            BufferedReader stdError = new BufferedReader(new 
            InputStreamReader(p.getErrorStream()));

           // read the output from the command
           //System.out.println("Here is the standard output of the command:\n");
           String s = null;
           //while ((s = stdInput.readLine()) != null) {
              // System.out.println(s);
               //txtaOutput.append("Download Successful");
              // String[] array = s.split(" ");
              // System.out.println(array[3].toString());
              // progValue += 1;
               
             //  progressBar.setValue(progValue);
         //  }

           // read any errors from the attempted command
           System.out.println("Here is the standard error of the command (if any):\n");
           while ((s = stdError.readLine()) != null) {
              System.out.println(s);
             
           }
           
           dl.setVisible(false);
           dl.setEnabled(false);
           JOptionPane.showMessageDialog(null, "Download Successfull"); 
           jButton2.setEnabled(true);
           jButton1.setEnabled(false);
            cmbFormat.setEnabled(false);
            cmbFormat.removeAllItems();
           
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
         
         
         
         
         
         
         
         
         
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cmbFormat.removeAllItems();
           String url = "" ;
         //String VideoF = "22";
         int progValue = 0;
         url = txtUrl.getText();
         if(url.isEmpty() == true){
             JOptionPane.showMessageDialog(null, "Please Enter an Youtube url first");
         }
         
         try {
            //cmd = ["/bin/bash","-c", " ps"];
            Process p = Runtime.getRuntime().exec("youtube-dl -F "+ url);
            BufferedReader stdInput = new BufferedReader(new 
            InputStreamReader(p.getInputStream()));
            BufferedReader stdError = new BufferedReader(new 
            InputStreamReader(p.getErrorStream()));

           // read the output from the command
           //System.out.println("Here is the standard output of the command:\n");
           String s = null;
           ArrayList<String> getInfos = new ArrayList<String>();
           while ((s = stdInput.readLine()) != null) {
               //System.out.println(s);
               //txtaOutput.append("Download Successful");
               getInfos.add(s);
               progValue += 10;
               
               progressBar.setValue(progValue);
               
           }
           
           //
          for(int i =5;i<getInfos.size();i++){
             //System.out.println("Line "+i + " ->"+getInfos.get(i));
             //getResult(getInfos.get(i));
             String cItem = getResult(getInfos.get(i))[0]+getResult(getInfos.get(i))[1];
             cmbFormat.addItem(cItem);
             cmbFormat.setEnabled(true);
          }
          
           
          
          
               
           
           // read any errors from the attempted command
           System.out.println("Here is the standard error of the command (if any):\n");
           while ((s = stdError.readLine()) != null) {
              System.out.println(s);
             
           }
         
            
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormatActionPerformed
        Object obj = evt.getSource();
        
        if(obj == cmbFormat){
            if(cmbFormat.getSelectedIndex() > 0){
                jButton1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cmbFormatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       About about = new About();
       about.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public String[] getResult(String st){
        String[] s = st.split(" ");
        String code;
         String format = "";
         String type = "";
         String siz = "";
         //System.out.println("Code:"+s[0]);
         code = s[0];
         
         // Searching Formate

         for(int fs = 0;fs <40;fs++){
             try{
                 if((s[fs].contains("webm") && s[fs].length() <=4)  || (s[fs].contains("m4a")&& s[fs].length() <=4) || (s[fs].contains("3gp")&& s[fs].length() <=4) || (s[fs].contains("mp4")&& s[fs].length() <=4)){
                      // System.out.println("-Formate:"+s[fs]);
                       format = s[fs];
                    }
                  
             }catch(Exception ex){
                
            }
         }

         //Searching Formate End Here
         
         // Searching Type
         for(int fs = 0;fs <40;fs++){
             try{
                 if(s[fs].contains("144p") ||s[fs].contains("240p") || s[fs].contains("360p") || s[fs].contains("480p") || s[fs].contains("720p")
               || s[fs].contains("1080p") || s[fs].contains("small") || s[fs].contains("medium") || s[fs].contains("best"))
                {
                  // System.out.println("-Type:"+s[fs]);
                   type = s[fs];
                }
             }catch(Exception ex){
                
            }
             
         }
         // Type Searching End here
         
         // Searching Size
         for(int fs = 0;fs <40;fs++){
            try{
             if(s[fs].contains("MiB")){
               //System.out.println("-Size:"+s[fs]);  
               siz = s[fs];
             }
         
            }catch(Exception ex){
                
            }
         }
         // Searching Size Ended
         String[] result = {code+" ->"," ["+format +"] ["+type +"] ["+siz+"]"};
         
       return result;
         
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFormat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
